version: '2'
services:
  app:
    image: blindsidenetwks/bigbluetutor-server:latest
    env_file:
      - .env
    ports:
     - "6020:6020"
    volumes:
     - '.:/usr/src/app'
     - '/usr/src/app/node_modules'
    command: npm start --production
