version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    volumes:
     - '.:/usr/src/app'
    command: npm start --production
    depends_on:
      - deepstreamio
  deepstreamio:
    image: deepstreamio/deepstream.io
    ports:
     - "6020:6020"
