version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
     - "6020:6020"
    volumes:
     - '.:/usr/src/app'
    command: npm start --development
    depends_on:
      - rethinkdb
  rethinkdb:
    image: rethinkdb
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"
