version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    ports:
     - 6020:6020
    volumes:
     - '.:/usr/src/app'
    command: npm start --production
