# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - type: shell
        name: Install RethinkDB
        command: |
          sudo apt-get -y install lsb-core
          lsb_release -a
          echo "deb http://download.rethinkdb.com/apt `lsb_release -cs` main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
          wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install rethinkdb
          sudo cp /etc/rethinkdb/default.conf.sample /etc/rethinkdb/instances.d/instance1.conf
          echo "cache-size=128" | sudo tee --append /etc/rethinkdb/instances.d/instance1.conf
          echo "no-http-admin" | sudo tee --append /etc/rethinkdb/instances.d/instance1.conf
          sudo /etc/init.d/rethinkdb restart
          sleep 5

      - type: shell
        name: RethinkDB Python driver setup
        command: |
          sudo apt-get install python3-pip
          sudo pip3 install rethinkdb python-dotenv

      - checkout

      - type: shell
        name: App setup
        command: |
          cp dotenv .env
          npm install
          npm run db:createtables

      #- run: npm -d start

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      #- run: yarn test

      - deploy:
          name: Build docker image
          command: |
            if [[ $CIRCLE_BRANCH == "master" && ${CI_PULL_REQUEST} == "" ]]; then
              echo "Docker image will be created. Enabling sudo for docker"
              echo sudo > ~/sudo
              ls -al
              ls -al scripts
              sudo ./scripts/build_image_master.sh
            else
              echo "Docker image won't be created. Enabling sudo for docker"
              echo "${CIRCLE_BRANCH}"
              echo "${CI_PULL_REQUEST}"
            fi
